// jugadoresData.js
const jugadoresMundial = [
    // --- AUSTRALIA ---
    ['Aiden O\'Neill', 'Australia', '🇦🇺', 'Mediocampista', 'fotos/aus_oneill.jpg', 'comun'],
    ['Alessandro Circati', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_circa.jpg', 'comun'],
    ['Aziz Behich', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_behich.jpg', 'rara'],
    ['Cameron Burgess', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_burges.jpg', 'comun'],
    ['Craig Goodwin', 'Australia', '🇦🇺', 'Delantero', 'fotos/aus_goodwin.jpg', 'rara'],
    ['Harry Souttar', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_souttar.jpg', 'rara'],
    ['Jackson Irvine', 'Australia', '🇦🇺', 'Mediocampista', 'fotos/aus_irvine.jpg', 'rara'],
    ['Jordan Bos', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_bos.jpg', 'comun'],
    ['Kusini Yengi', 'Australia', '🇦🇺', 'Delantero', 'fotos/aus_yengi.jpg', 'comun'],
    ['Lewis Miller', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_miller.jpg', 'comun'],
    ['Mathew Ryan', 'Australia', '🇦🇺', 'Arquero', 'fotos/aus_ryan.jpg', 'epica'],
    ['Milos Degenek', 'Australia', '🇦🇺', 'Defensor', 'fotos/aus_degenek.jpg', 'comun'],
    ['Nestory Irankunda', 'Australia', '🇦🇺', 'Delantero', 'fotos/aus_irankun.jpg', 'legendaria'],

    // --- ARGENTINA ---
    ['Lionel Messi', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_messi.jpg', 'legendaria'],
    ['Emiliano Martínez', 'Argentina', '🇦🇷', 'Arquero', 'fotos/arg_martinez.jpg', 'epica'],
    ['Rodrigo De Paul', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_paul.jpg', 'epica'],
    ['Julián Álvarez', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_alvarez.jpg', 'epica'],
    ['Lautaro Martínez', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_martinez-.jpg', 'epica'],
    ['Alexis Mac Allister', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_allister.jpg', 'rara'],
    ['Enzo Fernández', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_fernandez.jpg', 'rara'],
    ['Cristian Romero', 'Argentina', '🇦🇷', 'Defensor', 'fotos/arg_romero.jpg', 'epica'],
    ['Nicolas Gonzalez', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_gonzalez.jpg', 'comun'],
    ['Franco Mastantuono', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_mastantuono.jpg', 'rara'],
    ['Exequiel Palacios', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_palacios.jpg', 'comun'],
    ['Leandro Paredes', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_paredes.jpg', 'rara'],
    ['Nico Paz', 'Argentina', '🇦🇷', 'Mediocampista', 'fotos/arg_paz.jpg', 'rara'],
    ['Giuliano Simeone', 'Argentina', '🇦🇷', 'Delantero', 'fotos/arg_simeone.jpg', 'comun'],
    
    // --- BOSNIA Y HERZEGOVINA ---
    ['Samed Baždar', 'Bosnia y Herzegovina', '🇧🇦', 'Delantero', 'fotos/bos_bazdar.jpg', 'comun'],
    ['Benjamin Tahirović', 'Bosnia y Herzegovina', '🇧🇦', 'Mediocampista', 'fotos/bos_tahirovic.jpg', 'rara'],
    ['Edin Džeko', 'Bosnia y Herzegovina', '🇧🇦', 'Delantero', 'fotos/bos_dzeko.jpg', 'epica'],
    ['Amir Hadžiahmetović', 'Bosnia y Herzegovina', '🇧🇦', 'Mediocampista', 'fotos/bos_hadziahmetovic.jpg', 'comun'],
    ['Ivan Bašić', 'Bosnia y Herzegovina', '🇧🇦', 'Mediocampista', 'fotos/bos_basic.jpg', 'comun'],
    ['Sead Kolašinac', 'Bosnia y Herzegovina', '🇧🇦', 'Defensor', 'fotos/bos_kolasinac.jpg', 'rara'],
    ['Amar Memić', 'Bosnia y Herzegovina', '🇧🇦', 'Mediocampista', 'fotos/bos_memic.jpg', 'comun'],
    ['Tarik Muharemovic', 'Bosnia y Herzegovina', '🇧🇦', 'Defensor', 'fotos/bos_muharemovic.jpg', 'comun'],
    ['Nihad Mujakić', 'Bosnia y Herzegovina', '🇧🇦', 'Defensor', 'fotos/bos_mujakic.jpg', 'comun'],
    ['Ivan Šunjić', 'Bosnia y Herzegovina', '🇧🇦', 'Mediocampista', 'fotos/bos_sunjic.jpg', 'comun'],
    ['Haris Tabaković', 'Bosnia y Herzegovina', '🇧🇦', 'Delantero', 'fotos/bos_tabakovic.jpg', 'comun'],
    ['Nikola Vasilj', 'Bosnia y Herzegovina', '🇧🇦', 'Arquero', 'fotos/bos_vasilj.jpg', 'comun'],
    
    // --- BÉLGICA ---
    ['Kevin de Bruyne', 'Bélgica', '🇧🇪', 'Mediocampista', 'fotos/bel_bruyne.jpg', 'legendaria'],
    ['Timothy Castagne', 'Bélgica', '🇧🇪', 'Defensor', 'fotos/bel_castagne.jpg', 'rara'],
    ['Maxim de Cuyper', 'Bélgica', '🇧🇪', 'Mediocampista', 'fotos/bel_cuyper.jpg', 'comun'],
    ['Zeno Debast', 'Bélgica', '🇧🇪', 'Defensor', 'fotos/bel_debast.jpg', 'rara'],
    ['Jeremy Doku', 'Bélgica', '🇧🇪', 'Delantero', 'fotos/bel_doku.jpg', 'epica'],
    ['Romelu Lukaku', 'Bélgica', '🇧🇪', 'Delantero', 'fotos/bel_lakaku.jpg', 'legendaria'],
    ['Brandon Mechele', 'Bélgica', '🇧🇪', 'Defensor', 'fotos/bel_mechele.jpg', 'comun'],
    ['Thomas Meunier', 'Bélgica', '🇧🇪', 'Defensor', 'fotos/bel_meunier.jpg', 'rara'],
    ['Amadou Onana', 'Bélgica', '🇧🇪', 'Arquero', 'fotos/bel_onana.jpg', 'epica'],
    ['Lois Openda', 'Bélgica', '🇧🇪', 'Delantero', 'fotos/bel_openda.jpg', 'epica'],
    ['Nicolas Raskin', 'Bélgica', '🇧🇪', 'Mediocampista', 'fotos/bel_raskin.jpg', 'comun'],
    ['Alexis Saelemaekers', 'Bélgica', '🇧🇪', 'Delantero', 'fotos/bel_saelemaekers.jpg', 'rara'],
    ['Arthur Theate', 'Bélgica', '🇧🇪', 'Defensor', 'fotos/bel_theate.jpg', 'rara'],
    ['Youri Tielemans', 'Bélgica', '🇧🇪', 'Mediocampista', 'fotos/bel_tielemans.jpg', 'epica'],
    ['Hans Vanaken', 'Bélgica', '🇧🇪', 'Mediocampista', 'fotos/bel_vanaken.jpg', 'comun'],

    // --- CHEQUIA ---
    ['Vaclav Cerny', 'Chequia', '🇨🇿', 'Delantero', 'fotos/che_cerny.jpg', 'rara'],
    ['Lukas Cerv', 'Chequia', '🇨🇿', 'Mediocampista', 'fotos/che_cerv.jpg', 'comun'],
    ['Tomas Chory', 'Chequia', '🇨🇿', 'Delantero', 'fotos/che_chory.jpg', 'comun'],
    ['Adam Hlozek', 'Chequia', '🇨🇿', 'Delantero', 'fotos/che_hlozek.jpg', 'epica'],
    ['Tomas Holes', 'Chequia', '🇨🇿', 'Mediocampista', 'fotos/che_holes.jpg', 'rara'],
    ['Matej Kovar', 'Chequia', '🇨🇿', 'Arquero', 'fotos/che_kovar.jpg', 'rara'],
    ['Ladislav Krejci', 'Chequia', '🇨🇿', 'Defensor', 'fotos/che_krejci.jpg', 'epica'],
    ['Lukas Provod', 'Chequia', '🇨🇿', 'Mediocampista', 'fotos/che_provod.jpg', 'rara'],
    ['Michal Sadilek', 'Chequia', '🇨🇿', 'Mediocampista', 'fotos/che_sadilek.jpg', 'rara'],
    ['Patrik Schick', 'Chequia', '🇨🇿', 'Delantero', 'fotos/che_schick.jpg', 'legendaria'],
    ['Jindrich Stanek', 'Chequia', '🇨🇿', 'Arquero', 'fotos/che_stanek.jpg', 'comun'],
    ['Pavel Sulc', 'Chequia', '🇨🇿', 'Mediocampista', 'fotos/che_sulc.jpg', 'comun'],
    ['Matej Vydra', 'Chequia', '🇨🇿', 'Delantero', 'fotos/che_vydra.jpg', 'comun'],
    ['Jaroslav Zeleny', 'Chequia', '🇨🇿', 'Defensor', 'fotos/che_zeleny.jpg', 'comun'],
    ['David Zima', 'Chequia', '🇨🇿', 'Defensor', 'fotos/che_zima.jpg', 'rara'],

    // --- COSTA DE MARFIL ---
    ['Simon Adingra', 'Costa de Marfil', '🇨🇮', 'Delantero', 'fotos/cm_adingra.jpg', 'rara'],
    ['Emmanuel Agbadou', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_agbadou.jpg', 'comun'],
    ['Willy Boly', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_boly.jpg', 'rara'],
    ['Amad Diallo', 'Costa de Marfil', '🇨🇮', 'Delantero', 'fotos/cm_diallo.jpg', 'epica'],
    ['Yan Diomande', 'Costa de Marfil', '🇨🇮', 'Delantero', 'fotos/cm_diomande.jpg', 'epica'],
    ['Ousmane Diomande', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_diomande--.jpg', 'epica'],
    ['Yahia Fofana', 'Costa de Marfil', '🇨🇮', 'Arquero', 'fotos/cm_fofana.jpg', 'epica'],
    ['Seko Fofana', 'Costa de Marfil', '🇨🇮', 'Mediocampista', 'fotos/cm_fofana-.jpg', 'rara'],
    ['Sébastien Haller', 'Costa de Marfil', '🇨🇮', 'Delantero', 'fotos/cm_haller.jpg', 'legendaria'],
    ['Ghislain Konan', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_konan.jpg', 'comun'],
    ['Odilon Kossounou', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_kossounou.jpg', 'rara'],
    ['Evan Ndicka', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_ndicka.jpg', 'epica'],
    ['Wilfried Singo', 'Costa de Marfil', '🇨🇮', 'Defensor', 'fotos/cm_singo.jpg', 'rara'],

    // --- COLOMBIA ---
    ['Jhon Arias', 'Colombia', '🇨🇴', 'Defensor', 'fotos/col_arias.jpg', 'epica'],
    ['Santiago Arias', 'Colombia', '🇨🇴', 'Defensor', 'fotos/col_arias-.jpg', 'rara'],
    ['Jorge Carrascal', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_carrascal.jpg', 'rara'],
    ['Kevin Castaño', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_castaño.jpg', 'comun'],
    ['Jhon Córdoba', 'Colombia', '🇨🇴', 'Delantero', 'fotos/col_cordoba.jpg', 'rara'],
    ['Luis Díaz', 'Colombia', '🇨🇴', 'Delantero', 'fotos/col_diaz.jpg', 'legendaria'],
    ['Jefferson Lerma', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_lerma.jpg', 'epica'],
    ['Daniel Muñoz', 'Colombia', '🇨🇴', 'Defensor', 'fotos/col_muñoz.jpg', 'epica'],
    ['David Ospina', 'Colombia', '🇨🇴', 'Arquero', 'fotos/col_ospina.jpg', 'rara'],
    ['Juan Fernando Quintero', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_quintero.jpg', 'epica'],
    ['Richard Ríos', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_rios.jpg', 'epica'],
    ['James Rodríguez', 'Colombia', '🇨🇴', 'Mediocampista', 'fotos/col_rodriguez.jpg', 'legendaria'],
    ['Jhon Durán', 'Colombia', '🇨🇴', 'Delantero', 'fotos/col_suarez.jpg', 'epica'],
    ['Camilo Vargas', 'Colombia', '🇨🇴', 'Arquero', 'fotos/col_vargas.jpg', 'epica'],

    // --- ECUADOR ---
    ['Nilson Angulo', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_angulo.jpg', 'comun'],
    ['Moises Caicedo', 'Ecuador', '🇪🇨', 'Mediocampista', 'fotos/ecu_caicedo.jpg', 'legendaria'],
    ['Leonardo Campana', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_campana.jpg', 'rara'],
    ['Alan Franco', 'Ecuador', '🇪🇨', 'Mediocampista', 'fotos/ecu_franco.jpg', 'rara'],
    ['Hernán Galíndez', 'Ecuador', '🇪🇨', 'Arquero', 'fotos/ecu_galindez.jpg', 'epica'],
    ['Alan Minda', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_minda.jpg', 'rara'],
    ['Joel Ordóñez', 'Ecuador', '🇪🇨', 'Defensor', 'fotos/ecu_ordoñez.jpg', 'rara'],
    ['Kendry Páez', 'Ecuador', '🇪🇨', 'Mediocampista', 'fotos/ecu_paez.jpg', 'epica'],
    ['Gonzalo Plata', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_plata.jpg', 'epica'],
    ['Kevin Rodríguez', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_rodriguez.jpg', 'comun'],
    ['Enner Valencia', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_valencia.jpg', 'legendaria'],
    ['Gonzalo Valle', 'Ecuador', '🇪🇨', 'Arquero', 'fotos/ecu_valle.jpg', 'comun'],
    ['Pedro Vite', 'Ecuador', '🇪🇨', 'Mediocampista', 'fotos/ecu_vite.jpg', 'rara'],
    ['John Yeboah', 'Ecuador', '🇪🇨', 'Delantero', 'fotos/ecu_yeboah.jpg', 'rara'],

    // --- ESPAÑA ---
    ['Dani Carvajal', 'España', '🇪🇸', 'Defensor', 'fotos/esp_carvajal.jpg', 'legendaria'],
    ['Marc Cucurella', 'España', '🇪🇸', 'Defensor', 'fotos/esp_cucurella.jpg', 'epica'],
    ['Mikel Merino', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_merino.jpg', 'rara'],
    ['Álvaro Morata', 'España', '🇪🇸', 'Delantero', 'fotos/esp_morata.jpg', 'rara'],
    ['Dani Olmo', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_olmo.jpg', 'epica'],
    ['Mikel Oyarzabal', 'España', '🇪🇸', 'Delantero', 'fotos/esp_oyarzabal.jpg', 'rara'],
    ['Pedri', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_pedri.jpg', 'epica'],
    ['Rodri', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_rodri.jpg', 'legendaria'],
    ['Fabian Ruiz', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_ruiz.jpg', 'epica'],
    ['Unai Simón', 'España', '🇪🇸', 'Arquero', 'fotos/esp_simon.jpg', 'epica'],
    ['Ferran Torres', 'España', '🇪🇸', 'Delantero', 'fotos/esp_torres.jpg', 'rara'],
    ['Nico Williams', 'España', '🇪🇸', 'Delantero', 'fotos/esp_williams.jpg', 'legendaria'],
    ['Lamine Yamal', 'España', '🇪🇸', 'Delantero', 'fotos/esp_yamal.jpg', 'legendaria'],
    ['Martin Zubimendi', 'España', '🇪🇸', 'Mediocampista', 'fotos/esp_zubimendi.jpg', 'rara'],
    
    // --- FRANCIA ---
    ['Bradley Barcola', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_barcola.jpg', 'epica'],
    ['Eduardo Camavinga', 'Francia', '🇫🇷', 'Mediocampista', 'fotos/fra_camavinga.jpg', 'epica'],
    ['Kingsley Coman', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_coman.jpg', 'rara'],
    ['Ousmane Dembélé', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_dembele.jpg', 'legendaria'],
    ['Lucas Digne', 'Francia', '🇫🇷', 'Defensor', 'fotos/fra_digne.jpg', 'rara'],
    ['Desiré Doué', 'Francia', '🇫🇷', 'Mediocampista', 'fotos/fra_doue.jpg', 'rara'],
    ['Hugo Ekitike', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_ekitike.jpg', 'rara'],
    ['Manu Koné', 'Francia', '🇫🇷', 'Mediocampista', 'fotos/fra_kone.jpg', 'comun'],
    ['Mike Maignan', 'Francia', '🇫🇷', 'Arquero', 'fotos/fra_maignan.jpg', 'epica'],
    ['Kylian Mbappé', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_mbappe.jpg', 'legendaria'],
    ['Michael Olise', 'Francia', '🇫🇷', 'Delantero', 'fotos/fra_olise.jpg', 'epica'],
    ['Adrien Rabiot', 'Francia', '🇫🇷', 'Mediocampista', 'fotos/fra_rabiot.jpg', 'rara'],
    ['Aurélien Tchouaméni', 'Francia', '🇫🇷', 'Mediocampista', 'fotos/fra_tchuamani.jpg', 'epica'],
    ['Dayot Upamecano', 'Francia', '🇫🇷', 'Defensor', 'fotos/fra_upamecano.jpg', 'rara'],

    // --- INGLATERRA ---
    ['Jude Bellingham', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Mediocampista', 'fotos/ing_bellingham.jpg', 'legendaria'],
    ['Dan Burn', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Defensor', 'fotos/ing_burn.jpg', 'rara'],
    ['Phil Foden', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_foden.jpg', 'legendaria'],
    ['Anthony Gordon', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_gordon.jpg', 'rara'],
    ['Marc Guéhi', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Defensor', 'fotos/ing_guehi.jpg', 'epica'],
    ['Dean Henderson', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Arquero', 'fotos/ing_henderson.jpg', 'rara'],
    ['Harry Kane', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_kane.jpg', 'legendaria'],
    ['Cole Palmer', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Mediocampista', 'fotos/ing_palmer.jpg', 'legendaria'],
    ['Jordan Pickford', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Arquero', 'fotos/ing_pickford.jpg', 'epica'],
    ['Marcus Rashford', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_rashford.jpg', 'epica'],
    ['Declan Rice', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Mediocampista', 'fotos/ing_rice.jpg', 'epica'],
    ['Morgan Rogers', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Mediocampista', 'fotos/ing_rogers.jpg', 'comun'],
    ['Bukayo Saka', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_saka.jpg', 'legendaria'],
    ['John Stones', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Defensor', 'fotos/ing_stones.jpg', 'epica'],
    ['Ollie Watkins', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Delantero', 'fotos/ing_watkins.jpg', 'epica'],

    // --- MEXICO ---
    ['Luis Malagon', 'México', '🇲🇽', 'Arquero', 'fotos/mex_malagon.jpg', 'rara'],
    ['Edson Álvarez', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_alvarez.jpg', 'epica'],
    ['Chucky Lozano', 'México', '🇲🇽', 'Delantero', 'fotos/mex_lozano.jpg', 'rara'],
    ['César Montes', 'México', '🇲🇽', 'Defensor', 'fotos/mex_montes.jpg', 'comun'],
    ['Carlos Rodriguez', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_rodriguez.jpg', 'comun'],
    ['Diego Lainez', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_lainez.jpg', 'comun'],
    ['Erick Sanchez', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_sanchez.jpg', 'comun'],
    ['Israel Reyes', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_reyes.jpg', 'comun'],
    ['Jesus Gallardo', 'México', '🇲🇽', 'Delantero', 'fotos/mex_gallardo.jpg', 'comun'],
    ['Marcelo Ruiz', 'México', '🇲🇽', 'Mediocampista', 'fotos/mex_ruiz.jpg', 'comun'],
    ['Santiago Gimenez', 'México', '🇲🇽', 'Delantero', 'fotos/mex_gimenez.jpg', 'epica'],
    ['Raul Jimenez', 'México', '🇲🇽', 'Delantero', 'fotos/mex_jimenez.jpg', 'rara'],
    ['Johan Vasquez', 'México', '🇲🇽', 'Delantero', 'fotos/mex_vasquez.jpg', 'comun'],
    ['Jorge Sanchez', 'México', '🇲🇽', 'Delantero', 'fotos/mex_sanchez1.jpg', 'comun'],
    ['Orbelin Pineda', 'México', '🇲🇽', 'Delantero', 'fotos/mex_pineda.jpg', 'comun'],

    // --- JAPÓN ---
    ['Junya Ito', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_ito.jpg', 'epica'],
    ['Daichi Kamada', 'Japón', '🇯🇵', 'Mediocampista', 'fotos/jap_kamada.jpg', 'epica'],
    ['Takefusa Kubo', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_kubo.jpg', 'legendaria'],
    ['Shuto Machino', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_machino.jpg', 'comun'],
    ['Takumi Minamino', 'Japón', '🇯🇵', 'Mediocampista', 'fotos/jap_minamino.jpg', 'epica'],
    ['Keito Nakamura', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_nakamura.jpg', 'rara'],
    ['Kaishu Sano', 'Japón', '🇯🇵', 'Mediocampista', 'fotos/jap_sano.jpg', 'comun'],
    ['Yuki Soma', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_soma.jpg', 'comun'],
    ['Zion Suzuki', 'Japón', '🇯🇵', 'Arquero', 'fotos/jap_suzuki.jpg', 'rara'],
    ['Ao Tanaka', 'Japón', '🇯🇵', 'Mediocampista', 'fotos/jap_tanaka.jpg', 'rara'],
    ['Shogo Taniguchi', 'Japón', '🇯🇵', 'Defensor', 'fotos/jap_taniguchi.jpg', 'rara'],
    ['Ayase Ueda', 'Japón', '🇯🇵', 'Delantero', 'fotos/jap_ueda.jpg', 'epica'],
    ['Kota Watanabe', 'Japón', '🇯🇵', 'Mediocampista', 'fotos/jap_watanabe.jpg', 'comun'],

    // --- NORUEGA ---
    ['Kristoffer Ajer', 'Noruega', '🇳🇴', 'Defensor', 'fotos/nor_ajer.jpg', 'rara'],
    ['Patrick Berg', 'Noruega', '🇳🇴', 'Mediocampista', 'fotos/nor_berg.jpg', 'comun'],
    ['Sander Berge', 'Noruega', '🇳🇴', 'Mediocampista', 'fotos/nor_berge.jpg', 'rara'],
    ['Oscar Bobb', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_bobb.jpg', 'epica'],
    ['Aron Dønnum', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_donnum.jpg', 'comun'],
    ['Erling Haaland', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_haaland.jpg', 'legendaria'],
    ['Torbiørn Heggem', 'Noruega', '🇳🇴', 'Defensor', 'fotos/nor_heggem.jpg', 'comun'],
    ['Jørgen Strand Larsen', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_larsen.jpg', 'rara'],
    ['Antonio Nusa', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_nusa.jpg', 'epica'],
    ['Martin Ødegaard', 'Noruega', '🇳🇴', 'Mediocampista', 'fotos/nor_odegaard.jpg', 'legendaria'],
    ['Leo Østigård', 'Noruega', '🇳🇴', 'Defensor', 'fotos/nor_ostigard.jpg', 'rara'],
    ['Andreas Schjelderup', 'Noruega', '🇳🇴', 'Delantero', 'fotos/nor_schjelderup.jpg', 'rara'],
    ['Morten Thorsby', 'Noruega', '🇳🇴', 'Mediocampista', 'fotos/nor_thorsby.jpg', 'rara'],
    ['David Møller Wolfe', 'Noruega', '🇳🇴', 'Defensor', 'fotos/nor_wolfe.jpg', 'comun'],

    // --- PAÍSES BAJOS ---
    ['Memphis Depay', 'Países Bajos', '🇳🇱', 'Delantero', 'fotos/pai_depay.jpg', 'epica'],
    ['Virgil van Dijk', 'Países Bajos', '🇳🇱', 'Defensor', 'fotos/pai_dijk.jpg', 'legendaria'],
    ['Denzel Dumfries', 'Países Bajos', '🇳🇱', 'Defensor', 'fotos/pai_dumfries.jpg', 'epica'],
    ['Ryan Gravenberch', 'Países Bajos', '🇳🇱', 'Mediocampista', 'fotos/pai_gravenberch.jpg', 'rara'],
    ['Jan Paul van Hecke', 'Países Bajos', '🇳🇱', 'Defensor', 'fotos/pai_hecke.jpg', 'comun'],
    ['Frenkie de Jong', 'Países Bajos', '🇳🇱', 'Mediocampista', 'fotos/pai_jong.jpg', 'legendaria'],
    ['Justin Kluivert', 'Países Bajos', '🇳🇱', 'Delantero', 'fotos/pai_kluivert.jpg', 'rara'],
    ['Teun Koopmeiners', 'Países Bajos', '🇳🇱', 'Mediocampista', 'fotos/pai_koopmeiners.jpg', 'epica'],
    ['Donyell Malen', 'Países Bajos', '🇳🇱', 'Delantero', 'fotos/pai_malen.jpg', 'rara'],
    ['Tijjani Reijnders', 'Países Bajos', '🇳🇱', 'Mediocampista', 'fotos/pai_reijnders.jpg', 'epica'],
    ['Xavi Simons', 'Países Bajos', '🇳🇱', 'Mediocampista', 'fotos/pai_simons.jpg', 'legendaria'],
    ['Micky van de Ven', 'Países Bajos', '🇳🇱', 'Defensor', 'fotos/pai_ven.jpg', 'epica'],
    ['Bart Verbruggen', 'Países Bajos', '🇳🇱', 'Arquero', 'fotos/pai_verbruggen.jpg', 'epica'],
    ['Wout Weghorst', 'Países Bajos', '🇳🇱', 'Delantero', 'fotos/pai_weghorst.jpg', 'rara'],

    // --- PORTUGAL ---
    ['João Cancelo', 'Portugal', '🇵🇹', 'Defensor', 'fotos/por_cancelo.jpg', 'epica'],
    ['Diogo Costa', 'Portugal', '🇵🇹', 'Arquero', 'fotos/por_costa.jpg', 'epica'],
    ['Diogo Dalot', 'Portugal', '🇵🇹', 'Defensor', 'fotos/por_dalot.jpg', 'rara'],
    ['Rúben Dias', 'Portugal', '🇵🇹', 'Defensor', 'fotos/por_dias.jpg', 'legendaria'],
    ['João Félix', 'Portugal', '🇵🇹', 'Delantero', 'fotos/por_felix.jpg', 'rara'],
    ['Bruno Fernandes', 'Portugal', '🇵🇹', 'Mediocampista', 'fotos/por_fernandes.jpg', 'legendaria'],
    ['Gonçalo Inácio', 'Portugal', '🇵🇹', 'Defensor', 'fotos/por_inacio.jpg', 'rara'],
    ['Nuno Mendes', 'Portugal', '🇵🇹', 'Defensor', 'fotos/por_mendes.jpg', 'epica'],
    ['Rúben Neves', 'Portugal', '🇵🇹', 'Mediocampista', 'fotos/por_neves-.jpg', 'rara'],
    ['Joao Neves', 'Portugal', '🇵🇹', 'Mediocampista', 'fotos/por_neves.jpg', 'epica'],
    ['Cristiano Ronaldo', 'Portugal', '🇵🇹', 'Delantero', 'fotos/por_ronaldo.jpg', 'legendaria'],
    ['Bernardo Silva', 'Portugal', '🇵🇹', 'Mediocampista', 'fotos/por_silva.jpg', 'legendaria'],
    ['Trincão', 'Portugal', '🇵🇹', 'Delantero', 'fotos/por_trincao.jpg', 'comun'],
    ['Vitinha', 'Portugal', '🇵🇹', 'Mediocampista', 'fotos/por_vitinha.jpg', 'epica'],

    // --- ESTADOS UNIDOS ---
    ['Brenden Aaronson', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_aaronson.jpg', 'comun'],
    ['Tyler Adams', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_adams.jpg', 'rara'],
    ['Cristian Roldan', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_roldan.jpg', 'comun'],
    ['Diego Luna', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_luna.jpg', 'rara'],
    ['Folarin Balogun', 'Estados Unidos', '🇺🇸', 'Delantero', 'fotos/usa_balogun.jpg', 'rara'],
    ['Alejandro Zendejas', 'Estados Unidos', '🇺🇸', 'Delantero', 'fotos/usa_freeman.jpg', 'comun'],
    ['Matt Freese', 'Estados Unidos', '🇺🇸', 'Arquero', 'fotos/usa_freese.jpg', 'comun'],  
    ['Weston McKennie', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_mckennie.jpg', 'rara'],
    ['Mark McKenzie', 'Estados Unidos', '🇺🇸', 'Defensor', 'fotos/usa_mckenzie.jpg', 'comun'],
    ['Ricardo Pepi', 'Estados Unidos', '🇺🇸', 'Delantero', 'fotos/usa_pepi.jpg', 'comun'],
    ['Christian Pulisic', 'Estados Unidos', '🇺🇸', 'Delantero', 'fotos/usa_pulisic.jpg', 'epica'],
    ['Chris Richards', 'Estados Unidos', '🇺🇸', 'Defensor', 'fotos/usa_richards.jpg', 'comun'],
    ['Antonee Robinson', 'Estados Unidos', '🇺🇸', 'Defensor', 'fotos/usa_robinson.jpg', 'comun'],
    ['Tanner Tessmann', 'Estados Unidos', '🇺🇸', 'Mediocampista', 'fotos/usa_tessmann.jpg', 'comun'],
    ['Tim Weah', 'Estados Unidos', '🇺🇸', 'Delantero', 'fotos/usa_weah.jpg', 'comun'],

    // --- CATAR ---
    ['Ahmed Alaaeldin', 'Catar', '🇶🇦', 'Delantero', 'fotos/qat_ahmed.jpg', 'comun'],
    ['Sultan Al-Brake', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_albrake.jpg', 'comun'],
    ['Almoez Ali', 'Catar', '🇶🇦', 'Delantero', 'fotos/qat_ali.jpg', 'legendaria'],
    ['Karim Boudiaf', 'Catar', '🇶🇦', 'Mediocampista', 'fotos/qat_boudiaf.jpg', 'rara'],
    ['Homam Ahmed', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_ganehi.jpg', 'comun'],
    ['Abdulaziz Hatem', 'Catar', '🇶🇦', 'Mediocampista', 'fotos/qat_hatem.jpg', 'rara'],
    ['Hassan Al-Haydos', 'Catar', '🇶🇦', 'Delantero', 'fotos/qat_haydos.jpg', 'epica'],
    ['Boualem Khoukhi', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_khoukhi.jpg', 'epica'],
    ['Assim Madibo', 'Catar', '🇶🇦', 'Mediocampista', 'fotos/qat_madibo.jpg', 'comun'],
    ['Lucas Mendes', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_mendes.jpg', 'rara'],
    ['Pedro Miguel', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_miguel.jpg', 'rara'],
    ['Tarek Salman', 'Catar', '🇶🇦', 'Defensor', 'fotos/qat_salman.jpg', 'comun'],
    ['Mohammed Waad', 'Catar', '🇶🇦', 'Mediocampista', 'fotos/qat_waad.jpg', 'rara'],
    
    // --- CANADÁ ---
    ['Alphonso Davies', 'Canadá', '🇨🇦', 'Defensor', 'fotos/can_davies.jpg', 'epica'],
    ['Samuel Adekugbe', 'Canadá', '🇨🇦', 'Defensor', 'fotos/can_adekugbe.jpg', 'comun'],
    ['Moise Bombito', 'Canadá', '🇨🇦', 'Defensor', 'fotos/can_bombito.jpg', 'rara'],
    ['Tajon Buchanan', 'Canadá', '🇨🇦', 'Mediocampista', 'fotos/can_buchanan.jpg', 'rara'],
    ['Mathieu Choiniere', 'Canadá', '🇨🇦', 'Mediocampista', 'fotos/can_choiniere.jpg', 'comun'],
    ['Derek Cornelius', 'Canadá', '🇨🇦', 'Defensor', 'fotos/can_cornelius.jpg', 'comun'],
    ['Cyle Larin', 'Canadá', '🇨🇦', 'Delantero', 'fotos/can_larin.jpg', 'comun'],
    ['Jonathan David', 'Canadá', '🇨🇦', 'Delantero', 'fotos/can_david.jpg', 'rara'],
    ['Dayne St. Clair', 'Canadá', '🇨🇦', 'Arquero', 'fotos/can_clair.jpg', 'comun'],
    ['Stephen Eustaquio', 'Canadá', '🇨🇦', 'Mediocampista', 'fotos/can_eustaquio.jpg', 'rara'],
    ['Ismael Kone', 'Canadá', '🇨🇦', 'Mediocampista', 'fotos/can_kone.jpg', 'comun'],
    ['Liam Millar', 'Canadá', '🇨🇦', 'Delantero', 'fotos/can_millar.jpg', 'comun'],
    ['Kamal Miller', 'Canadá', '🇨🇦', 'Defensor', 'fotos/can_miller.jpg', 'comun'],
    ['Jonathan Osorio', 'Canadá', '🇨🇦', 'Mediocampista', 'fotos/can_osorio.jpg', 'comun'],

    // --- BRASIL ---
    ['Alisson Becker', 'Brasil', '🇧🇷', 'Arquero', 'fotos/bra_becker.jpg', 'epica'],
    ['Gleison Bremer', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_bremer.jpg', 'rara'],
    ['Casemiro', 'Brasil', '🇧🇷', 'Mediocampista', 'fotos/bra_casemiro.jpg', 'epica'],
    ['Matheus Cunha', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_cunha.jpg', 'comun'],
    ['Danilo', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_danilo.jpg', 'comun'],
    ['Danilo R.', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_danilo-.jpg', 'comun'],
    ['Endrick', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_endrick.jpg', 'rara'],
    ['Fabinho', 'Brasil', '🇧🇷', 'Mediocampista', 'fotos/bra_fabinho.jpg', 'comun'],
    ['Bruno Guimarães', 'Brasil', '🇧🇷', 'Mediocampista', 'fotos/bra_guimaraes.jpg', 'rara'],
    ['Henrique', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_henriqe.jpg', 'comun'],
    ['Roger Ibáñez', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_ibañez.jpg', 'comun'],
    ['Gabriel Magalhães', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_magalhaes.jpg', 'rara'],
    ['Marquinhos', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_marquinhos.jpg', 'epica'],
    ['Gabriel Martinelli', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_martinelli.jpg', 'rara'],
    ['Ederson Moraes', 'Brasil', '🇧🇷', 'Arquero', 'fotos/bra_moraes.jpg', 'rara'],
    ['Neymar Jr', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_neymar.jpg', 'legendaria'],
    ['Lucas Paquetá', 'Brasil', '🇧🇷', 'Mediocampista', 'fotos/bra_paqueta.jpg', 'rara'],
    ['Andreas Pereira', 'Brasil', '🇧🇷', 'Mediocampista', 'fotos/bra_pereira.jpg', 'comun'],
    ['Raphinha', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_raphinha.jpg', 'epica'],
    ['Rayan', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_rayan.jpg', 'comun'],
    ['Alex Sandro', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_sandro.jpg', 'comun'],
    ['Santos', 'Brasil', '🇧🇷', 'Arquero', 'fotos/bra_santos.jpg', 'comun'],
    ['Igor Thiago', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_thiago.jpg', 'comun'],
    ['Vinícius Jr', 'Brasil', '🇧🇷', 'Delantero', 'fotos/bra_vinicius.jpg', 'legendaria'],
    ['Weverton', 'Brasil', '🇧🇷', 'Arquero', 'fotos/bra_weverton.jpg', 'comun'],
    ['Wesley', 'Brasil', '🇧🇷', 'Defensor', 'fotos/bra_wesley.jpg', 'comun'],

    // --- ESCOCIA ---
    ['Ryan Christie', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Mediocampista', 'fotos/esc_christie.jpg', 'rara'],
    ['Lyndon Dykes', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Delantero', 'fotos/esc_dykes.jpg', 'rara'],
    ['Lewis Ferguson', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Mediocampista', 'fotos/esc_ferguson.jpg', 'rara'],
    ['Angus Gunn', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Arquero', 'fotos/esc_gunn.jpg', 'epica'],
    ['Grant Hanley', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Defensor', 'fotos/esc_hanley.jpg', 'comun'],
    ['Jack Hendry', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Defensor', 'fotos/esc_hendry.jpg', 'rara'],
    ['John McGinn', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Mediocampista', 'fotos/esc_mcginn.jpg', 'epica'],
    ['Scott McKenna', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Defensor', 'fotos/esc_mckenna.jpg', 'comun'],
    ['Kenny McLean', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Mediocampista', 'fotos/esc_mclean.jpg', 'comun'],
    ['Scott McTominay', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Mediocampista', 'fotos/esc_mctominay.jpg', 'legendaria'],
    ['Anthony Ralston', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Defensor', 'fotos/esc_ralston.jpg', 'comun'],
    ['John Souttar', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Defensor', 'fotos/esc_souttar.jpg', 'rara'],
    
    // --- HAITÍ ---
    ['Ricardo Adé', 'Haití', '🇭🇹', 'Delantero', 'fotos/hai_ade.jpg', 'comun'],
    ['Carlens Arcus', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_arcus.jpg', 'comun'],
    ['Christopher Attvs', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_attvs.jpg', 'comun'], 
    ['Jean-Ricner Bellegarde', 'Haití', '🇭🇹', 'Mediocampista', 'fotos/hai_bellegarde.jpg', 'epica'],
    ['Josué Casimir', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_casimir.jpg', 'comun'],
    ['Don Deedson Louicius', 'Haití', '🇭🇹', 'Delantero', 'fotos/hai_deedson.jpg', 'comun'],
    ['Hannes Delcroix', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_delcroix.jpg', 'comun'],
    ['Jean-Kévin Duverne', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_duverne.jpg', 'rara'],
    ['Derrick Etienne Jr.', 'Haití', '🇭🇹', 'Mediocampista', 'fotos/hai_etienne_Jr.jpg', 'comun'],
    ['Martin Experience', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_experience.jpg', 'comun'],
    ['Danley Jean Jacques', 'Haití', '🇭🇹', 'Mediocampista', 'fotos/hai_jacques.jpg', 'comun'],
    ['Duke Lacroix', 'Haití', '🇭🇹', 'Defensor', 'fotos/hai_lacroix.jpg', 'comun'],
    ['Duckens Nazon', 'Haití', '🇭🇹', 'Delantero', 'fotos/hai_nazon.jpg', 'rara'],
    ['Leverton Pierre', 'Haití', '🇭🇹', 'Delantero', 'fotos/hai_pierre.jpg', 'comun'],
    ['Johny Placide', 'Haití', '🇭🇹', 'Arquero', 'fotos/hai_placide.jpg', 'rara'],

    // --- COREA DEL SUR ---
    ['Jens Castrop', 'Corea del Sur', '🇰🇷', 'Mediocampista', 'fotos/kor_castrop.jpg', 'comun'],
    ['Yumin Cho', 'Corea del Sur', '🇰🇷', 'Defensor', 'fotos/kor_cho.jpg', 'comun'],
    ['Heechan Hwang', 'Corea del Sur', '🇰🇷', 'Delantero', 'fotos/kor_hwang.jpg', 'epica'],
    ['Jaesung Lee', 'Corea del Sur', '🇰🇷', 'Mediocampista', 'fotos/kor_jLee.jpg', 'rara'],
    ['Hyeonwoo Jo', 'Corea del Sur', '🇰🇷', 'Arquero', 'fotos/kor_jo.jpg', 'rara'],
    ['Seunggyu Kim', 'Corea del Sur', '🇰🇷', 'Arquero', 'fotos/kor_kim.jpg', 'rara'],
    ['Kangin Lee', 'Corea del Sur', '🇰🇷', 'Mediocampista', 'fotos/kor_kLee.jpg', 'epica'],
    ['Hanbeom Lee', 'Corea del Sur', '🇰🇷', 'Defensor', 'fotos/kor_lee.jpg', 'comun'],
    ['Myungjae Lee', 'Corea del Sur', '🇰🇷', 'Defensor', 'fotos/kor_mLee.jpg', 'comun'],
    ['Hyeongyu Oh', 'Corea del Sur', '🇰🇷', 'Delantero', 'fotos/kor_oh.jpg', 'comun'],
    ['Seungho Paik', 'Corea del Sur', '🇰🇷', 'Mediocampista', 'fotos/kor_paik.jpg', 'comun'],
    ['Youngwoo Seol', 'Corea del Sur', '🇰🇷', 'Defensor', 'fotos/kor_seol.jpg', 'comun'],
    ['Heungmin Son', 'Corea del Sur', '🇰🇷', 'Delantero', 'fotos/kor_son.jpg', 'legendaria'],

    // --- PARAGUAY ---
    ['Omar Alderete', 'Paraguay', '🇵🇾', 'Defensor', 'fotos/par_alderete.jpg', 'rara'],
    ['Miguel Almirón', 'Paraguay', '🇵🇾', 'Delantero', 'fotos/par_almiron.jpg', 'epica'],
    ['Junior Alonso', 'Paraguay', '🇵🇾', 'Defensor', 'fotos/par_alonso.jpg', 'comun'],
    ['Fabián Balbuena', 'Paraguay', '🇵🇾', 'Defensor', 'fotos/par_balbuena.jpg', 'comun'],
    ['Juan José Cáceres', 'Paraguay', '🇵🇾', 'Defensor', 'fotos/par_caceres.jpg', 'comun'],
    ['Andrés Cubas', 'Paraguay', '🇵🇾', 'Mediocampista', 'fotos/par_cubas.jpg', 'comun'],
    ['Julio Enciso', 'Paraguay', '🇵🇾', 'Delantero', 'fotos/par_enciso.jpg', 'epica'],
    ['Roberto Fernández', 'Paraguay', '🇵🇾', 'Arquero', 'fotos/par_fernandez.jpg', 'comun'],
    ['Gustavo Gómez', 'Paraguay', '🇵🇾', 'Defensor', 'fotos/par_gGomez.jpg', 'rara'],
    ['Orlando Gill', 'Paraguay', '🇵🇾', 'Arquero', 'fotos/par_gill.jpg', 'comun'],
    ['Diego Gómez', 'Paraguay', '🇵🇾', 'Mediocampista', 'fotos/par_gomez.jpg', 'rara'],
    ['Ángel Romero', 'Paraguay', '🇵🇾', 'Delantero', 'fotos/par_romero.jpg', 'comun'],
    ['Ramón Sosa', 'Paraguay', '🇵🇾', 'Delantero', 'fotos/par_sosa.jpg', 'rara'],
    ['Mathías Villasanti', 'Paraguay', '🇵🇾', 'Mediocampista', 'fotos/par_villasanti.jpg', 'comun'],

    // --- SUIZA ---
    ['Michel Aebischer', 'Suiza', '🇨🇭', 'Mediocampista', 'fotos/sui_aebischer.jpg', 'rara'],
    ['Manuel Akanji', 'Suiza', '🇨🇭', 'Defensor', 'fotos/sui_akanji.jpg', 'legendaria'],
    ['Zeki Amdouni', 'Suiza', '🇨🇭', 'Delantero', 'fotos/sui_amdouni.jpg', 'rara'],
    ['Aurèle Amenda', 'Suiza', '🇨🇭', 'Defensor', 'fotos/sui_amenda.jpg', 'comun'],
    ['Nico Elvedi', 'Suiza', '🇨🇭', 'Defensor', 'fotos/sui_elvedi.jpg', 'rara'],
    ['Remo Freuler', 'Suiza', '🇨🇭', 'Mediocampista', 'fotos/sui_freuler.jpg', 'epica'],
    ['Gregor Kobel', 'Suiza', '🇨🇭', 'Arquero', 'fotos/sui_kobel.jpg', 'legendaria'],
    ['Joel Monteiro', 'Suiza', '🇨🇭', 'Delantero', 'fotos/sui_manzambi.jpg', 'comun'],
    ['Dan Ndoye', 'Suiza', '🇨🇭', 'Delantero', 'fotos/sui_ndoye.jpg', 'epica'],
    ['Fabian Rieder', 'Suiza', '🇨🇭', 'Mediocampista', 'fotos/sui_rieder.jpg', 'rara'],
    ['Ricardo Rodríguez', 'Suiza', '🇨🇭', 'Defensor', 'fotos/sui_rodriguez.jpg', 'epica'],
    ['Ruben Vargas', 'Suiza', '🇨🇭', 'Delantero', 'fotos/sui_vargas.jpg', 'epica'],
    ['Silvan Widmer', 'Suiza', '🇨🇭', 'Defensor', 'fotos/sui_widmer.jpg', 'rara'],
    ['Granit Xhaka', 'Suiza', '🇨🇭', 'Mediocampista', 'fotos/sui_xhaka.jpg', 'legendaria'],
    ['Denis Zakaria', 'Suiza', '🇨🇭', 'Mediocampista', 'fotos/sui_zakaria.jpg', 'epica'],

    // --- TÚNEZ ---
    ['Ali Abdi', 'Túnez', '🇹🇳', 'Defensor', 'fotos/tun_abdi.jpg', 'rara'],
    ['Elias Achouri', 'Túnez', '🇹🇳', 'Delantero', 'fotos/tun_achouri.jpg', 'rara'],
    ['Aymen Dahmen', 'Túnez', '🇹🇳', 'Arquero', 'fotos/tun_dahmen.jpg', 'comun'],
    ['Ismaël Gharbi', 'Túnez', '🇹🇳', 'Mediocampista', 'fotos/tun_gharbi.jpg', 'rara'],
    ['Aïssa Laïdouni', 'Túnez', '🇹🇳', 'Mediocampista', 'fotos/tun_laidouni.jpg', 'epica'],
    ['Sayfallah Ltaief', 'Túnez', '🇹🇳', 'Delantero', 'fotos/tun_ltaief.jpg', 'comun'],
    ['Rani Mastouri', 'Túnez', '🇹🇳', 'Delantero', 'fotos/tun_mastouri.jpg', 'comun'],
    ['Hannibal Mejbri', 'Túnez', '🇹🇳', 'Mediocampista', 'fotos/tun_mejbri.jpg', 'epica'],
    ['Yassine Meriah', 'Túnez', '🇹🇳', 'Defensor', 'fotos/tun_meriah.jpg', 'rara'],
    ['Haythem Jouini', 'Túnez', '🇹🇳', 'Delantero', 'fotos/tun_saad.jpg', 'comun'],
    ['Ferjani Sassi', 'Túnez', '🇹🇳', 'Mediocampista', 'fotos/tun_sassi.jpg', 'rara'],
    ['Ellyes Skhiri', 'Túnez', '🇹🇳', 'Mediocampista', 'fotos/tun_skhiri.jpg', 'legendaria'],
    ['Naïm Sliti', 'Túnez', '🇹🇳', 'Delantero', 'fotos/tun_sliti.jpg', 'rara'],
    ['Montassar Talbi', 'Túnez', '🇹🇳', 'Defensor', 'fotos/tun_talbi.jpg', 'epica'],
    ['Yan Valery', 'Túnez', '🇹🇳', 'Defensor', 'fotos/tun_valery.jpg', 'rara'],

    // --- ALEMANIA ---
    ['Jamal Musiala', 'Alemania', '🇩🇪', 'Mediocampista', 'fotos/ale_musiala.jpg', 'legendaria'],
    ['Florian Wirtz', 'Alemania', '🇩🇪', 'Mediocampista', 'fotos/ale_wirtz.jpg', 'legendaria'],
    ['Kai Havertz', 'Alemania', '🇩🇪', 'Delantero', 'fotos/ale_havertz.jpg', 'rara'],
    ['Leon Goretzka', 'Alemania', '🇩🇪', 'Mediocampista', 'fotos/ale_goretzka.jpg', 'rara'],
    ['Joshua Kimmich', 'Alemania', '🇩🇪', 'Mediocampista', 'fotos/ale_kimmich.jpg', 'epica'],
    ['Antonio Rüdiger', 'Alemania', '🇩🇪', 'Defensor', 'fotos/ale_rudiger.jpg', 'epica'],
    ['Marc-André ter Stegen', 'Alemania', '🇩🇪', 'Arquero', 'fotos/ale_stegen.jpg', 'epica'],
    ['Serge Gnabry', 'Alemania', '🇩🇪', 'Delantero', 'fotos/ale_gnabry.jpg', 'rara'],
    ['Maximilian Mittelstädt', 'Alemania', '🇩🇪', 'Defensor', 'fotos/ale_mittle.jpg', 'comun'],
    ['Felix Nmecha', 'Alemania', '🇩🇪', 'Mediocampista', 'fotos/ale_nmecha.jpg', 'comun'],
    ['Ridle Baku', 'Alemania', '🇩🇪', 'Defensor', 'fotos/ale_baku.jpg', 'comun'],
    ['Nico Schlotterbeck', 'Alemania', '🇩🇪', 'Defensor', 'fotos/ale_schlotterbeck.jpg', 'comun'],
    ['Nick Woltemade', 'Alemania', '🇩🇪', 'Delantero', 'fotos/ale_woltemade.jpg', 'comun'],
    ['Jonathan Tah', 'Alemania', '🇩🇪', 'Defensor', 'fotos/ale_tah.jpg', 'comun'],

    // --- URUGUAY ---
    ['Ronald Araújo', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_araujo.jpg', 'legendaria'],
    ['Maxi Araujo', 'Uruguay', '🇺🇾', 'Delantero', 'fotos/uru_araujo-.jpg', 'comun'],
    ['Rodrigo Bentancur', 'Uruguay', '🇺🇾', 'Mediocampista', 'fotos/uru_bentancur.jpg', 'epica'],
    ['Sebastián Cáceres', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_caceres.jpg', 'rara'],
    ['José María Giménez', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_gimenez.jpg', 'epica'],
    ['Alan Matturro', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_miele.jpg', 'comun'],
    ['Nahitan Nández', 'Uruguay', '🇺🇾', 'Mediocampista', 'fotos/uru_nandez.jpg', 'epica'],
    ['Darwin Núñez', 'Uruguay', '🇺🇾', 'Delantero', 'fotos/uru_nuñez.jpg', 'legendaria'],
    ['Mathías Olivera', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_olivera.jpg', 'rara'],
    ['Facundo Pellistri', 'Uruguay', '🇺🇾', 'Delantero', 'fotos/uru_pellistri.jpg', 'epica'],
    ['Sergio Rochet', 'Uruguay', '🇺🇾', 'Arquero', 'fotos/uru_rochet.jpg', 'epica'],
    ['Manuel Ugarte', 'Uruguay', '🇺🇾', 'Mediocampista', 'fotos/uru_ugarte.jpg', 'epica'],
    ['Federico Valverde', 'Uruguay', '🇺🇾', 'Mediocampista', 'fotos/uru_valverde.jpg', 'legendaria'],
    ['Guillermo Varela', 'Uruguay', '🇺🇾', 'Defensor', 'fotos/uru_varela.jpg', 'rara'],
    ['Federico Viñas', 'Uruguay', '🇺🇾', 'Delantero', 'fotos/uru_viñas.jpg', 'rara'],

    // --- TURQUÍA ---
    ['Yunus Akgun', 'Turquía', '🇹🇷', 'Delantero', 'fotos/tur_akgun.jpg', 'comun'],
    ['Kerem Akturkoglu', 'Turquía', '🇹🇷', 'Delantero', 'fotos/tur_akturkoglu.jpg', 'epica'],
    ['Kaan Ayhan', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_ayhan.jpg', 'comun'],
    ['Abdulkerim Bardakci', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_bardakci.jpg', 'comun'],
    ['Ugurcan Cakir', 'Turquía', '🇹🇷', 'Arquero', 'fotos/tur_cakir.jpg', 'comun'],
    ['Zeki Celik', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_celik.jpg', 'comun'],
    ['Merih Demiral', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_demiral.jpg', 'rara'],
    ['Irfan Can Kahveci', 'Turquía', '🇹🇷', 'Mediocampista', 'fotos/tur_kahveci.jpg', 'comun'],
    ['Arda Guler', 'Turquía', '🇹🇷', 'Mediocampista', 'fotos/tur_guler.jpg', 'epica'],
    ['Orkun Kokcu', 'Turquía', '🇹🇷', 'Mediocampista', 'fotos/tur_kokcu.jpg', 'rara'],
    ['Mert Muldur', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_muldur.jpg', 'comun'],
    ['Caglar Soyuncu', 'Turquía', '🇹🇷', 'Defensor', 'fotos/tur_soyuncu.jpg', 'rara'],
    ['Can Uzun', 'Turquía', '🇹🇷', 'Delantero', 'fotos/tur_uzun.jpg', 'comun'],
    ['Kenan Yildiz', 'Turquía', '🇹🇷', 'Delantero', 'fotos/tur_yildiz.jpg', 'rara'],
    ['Baris Alper Yilmaz', 'Turquía', '🇹🇷', 'Mediocampista', 'fotos/tur_yilmaz.jpg', 'comun'],

    // --- UZBEKISTÁN ---
    ['Khojiakbar Alijonov', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_alijonov.jpg', 'comun'],
    ['Khusniddin Aliqulov', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_aliqulov.jpg', 'rara'],
    ['Rustam Ashurmatov', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_ashurmatov.jpg', 'comun'],
    ['Khojimat Erkinov', 'Uzbekistán', '🇺🇿', 'Delantero', 'fotos/uzb_erkinov.jpg', 'rara'],
    ['Umar Eshmurodov', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_eshmurodov.jpg', 'comun'],
    ['Abbosbek Fayzullaev', 'Uzbekistán', '🇺🇿', 'Mediocampista', 'fotos/uzb_fayzullaev.jpg', 'epica'],
    ['Jamshid Iskanderov', 'Uzbekistán', '🇺🇿', 'Mediocampista', 'fotos/uzb_iskanderov.jpg', 'comun'],
    ['Jaloliddin Masharipov', 'Uzbekistán', '🇺🇿', 'Mediocampista', 'fotos/uzb_masharipov.jpg', 'rara'],
    ['Sherzod Nasrullaev', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_nasrullaev.jpg', 'comun'],
    ['Farrukh Sayfiev', 'Uzbekistán', '🇺🇿', 'Defensor', 'fotos/uzb_sayfiev.jpg', 'rara'],
    ['Igor Sergeev', 'Uzbekistán', '🇺🇿', 'Delantero', 'fotos/uzb_sergeev.jpg', 'rara'],
    ['Eldor Shomurodov', 'Uzbekistán', '🇺🇿', 'Delantero', 'fotos/uzb_shomurodov.jpg', 'legendaria'],
    ['Otabek Shukurov', 'Uzbekistán', '🇺🇿', 'Mediocampista', 'fotos/uzb_shukurov.jpg', 'epica'],
    ['Azizbek Turgunboev', 'Uzbekistán', '🇺🇿', 'Mediocampista', 'fotos/uzb_turgunboev.jpg', 'rara'],
    ['Oston Urunov', 'Uzbekistán', '🇺🇿', 'Delantero', 'fotos/uzb_urunov.jpg', 'rara'],
    
    // --- MARRUECOS ---
    ['Nayef Aguerd', 'Marruecos', '🇲🇦', 'Defensor', 'fotos/mar_aguerd.jpg', 'rara'],
    ['Sofyan Amrabat', 'Marruecos', '🇲🇦', 'Mediocampista', 'fotos/mar_amrabat.jpg', 'rara'],
    ['Yassine Bounou', 'Marruecos', '🇲🇦', 'Arquero', 'fotos/mar_bounou.jpg', 'epica'],
    ['Brahim Díaz', 'Marruecos', '🇲🇦', 'Mediocampista', 'fotos/mar_diaz.jpg', 'epica'],
    ['Abde Ezzalzouli', 'Marruecos', '🇲🇦', 'Delantero', 'fotos/mar_ezzalzouli.jpg', 'comun'],
    ['Ayoub El Kaabi', 'Marruecos', '🇲🇦', 'Delantero', 'fotos/mar_kaabi.jpg', 'rara'],
    ['Bilal El Khannouss', 'Marruecos', '🇲🇦', 'Mediocampista', 'fotos/mar_khannouss.jpg', 'comun'],
    ['Adam Masina', 'Marruecos', '🇲🇦', 'Defensor', 'fotos/mar_masina.jpg', 'comun'],
    ['Youssef En-Nesyri', 'Marruecos', '🇲🇦', 'Delantero', 'fotos/mar_nesyri.jpg', 'comun'],
    ['Ismael Saibari', 'Marruecos', '🇲🇦', 'Mediocampista', 'fotos/mar_saibari.jpg', 'comun'],
    ['Romain Saiss', 'Marruecos', '🇲🇦', 'Defensor', 'fotos/mar_saiss.jpg', 'comun'],
    ['Eliesse Ben Seghir', 'Marruecos', '🇲🇦', 'Mediocampista', 'fotos/mar_seghir.jpg', 'comun'],
    ['Jawad El Yamiq', 'Marruecos', '🇲🇦', 'Defensor', 'fotos/mar_yamiq.jpg', 'comun'],

    // --- ARGELIA ---
    ['Houssem Aouar', 'Argelia', '🇩🇿', 'Mediocampista', 'fotos/arg_aquar.jpg', 'rara'],
    ['Youcef Atal', 'Argelia', '🇩🇿', 'Defensor', 'fotos/arg_atal.jpg', 'comun'],
    ['Ismaël Bennacer', 'Argelia', '🇩🇿', 'Mediocampista', 'fotos/arg_bennacer.jpg', 'epica'],
    ['Saïd Benrahma', 'Argelia', '🇩🇿', 'Delantero', 'fotos/arg_benrahma.jpg', 'rara'],
    ['Ramy Bensebaini', 'Argelia', '🇩🇿', 'Defensor', 'fotos/arg_bensebaini.jpg', 'rara'],
    ['Hicham Boudaoui', 'Argelia', '🇩🇿', 'Mediocampista', 'fotos/arg_boudaqui.jpg', 'comun'],
    ['Baghdad Bounedjah', 'Argelia', '🇩🇿', 'Delantero', 'fotos/arg_bounedjah.jpg', 'comun'],
    ['Farès Chaïbi', 'Argelia', '🇩🇿', 'Mediocampista', 'fotos/arg_chaibi.jpg', 'comun'],
    ['Amine Gouiri', 'Argelia', '🇩🇿', 'Delantero', 'fotos/arg_gouiri.jpg', 'rara'],
    ['Mustapha Zeghba', 'Argelia', '🇩🇿', 'Arquero', 'fotos/arg_guendouz.jpg', 'comun'],
    ['Riyad Mahrez', 'Argelia', '🇩🇿', 'Delantero', 'fotos/arg_mahrez.jpg', 'legendaria'],
    ['Aïssa Mandi', 'Argelia', '🇩🇿', 'Defensor', 'fotos/arg_mandi.jpg', 'rara'],
    ['Nadjib Amine Tougai', 'Argelia', '🇩🇿', 'Defensor', 'fotos/arg_tougai.jpg', 'comun'],
    ['Ramiz Zerrouki', 'Argelia', '🇩🇿', 'Mediocampista', 'fotos/arg_zerrouki.jpg', 'comun'],

    // --- AUSTRIA ---
    ['David Alaba', 'Austria', '🇦🇹', 'Defensor', 'fotos/aus_alaba.jpg', 'legendaria'],
    ['Christoph Baumgartner', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_baumgartner.jpg', 'rara'],
    ['Kevin Danso', 'Austria', '🇦🇹', 'Defensor', 'fotos/aus_danso.jpg', 'rara'],
    ['Michael Gregoritsch', 'Austria', '🇦🇹', 'Delantero', 'fotos/aus_gregoritsch.jpg', 'comun'],
    ['Konrad Laimer', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_laimer.jpg', 'epica'],
    ['Philipp Lienhart', 'Austria', '🇦🇹', 'Defensor', 'fotos/aus_lienhart.jpg', 'comun'],
    ['Patrick Pentz', 'Austria', '🇦🇹', 'Arquero', 'fotos/aus_pentz.jpg', 'comun'],
    ['Stefan Posch', 'Austria', '🇦🇹', 'Defensor', 'fotos/aus_posch.jpg', 'rara'],
    ['Alexander Prass', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_prass.jpg', 'comun'],
    ['Marcel Sabitzer', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_sabitzer.jpg', 'epica'],
    ['Xaver Schlager', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_schlager-.jpg', 'rara'],
    ['Alexander Schlager', 'Austria', '🇦🇹', 'Arquero', 'fotos/aus_schlager.jpg', 'comun'], 
    ['Romano Schmid', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_schmid.jpg', 'comun'],
    ['Nicolas Seiwald', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_seiwald.jpg', 'comun'],
    ['Patrick Wimmer', 'Austria', '🇦🇹', 'Mediocampista', 'fotos/aus_wimmer.jpg', 'comun'],

    // --- ARABIA SAUDITA ---
    ['Saud Abdulhamid', 'Arabia Saudita', '🇸🇦', 'Defensor', 'fotos/ara_abdulhamid.jpg', 'rara'],
    ['Salem Al-Dawsari', 'Arabia Saudita', '🇸🇦', 'Mediocampista', 'fotos/ara_aldawsari.jpg', 'legendaria'],
    ['Nasser Aldawsari', 'Arabia Saudita', '🇸🇦', 'Mediocampista', 'fotos/ara_aldawsari-.jpg', 'comun'], 
    ['Moteb Al-Harbi', 'Arabia Saudita', '🇸🇦', 'Defensor', 'fotos/ara_alharbi.jpg', 'comun'],
    ['Fahad Al-Johani', 'Arabia Saudita', '🇸🇦', 'Delantero', 'fotos/ara_aljohani.jpg', 'comun'],
    ['Musab Al-Juwayr', 'Arabia Saudita', '🇸🇦', 'Mediocampista', 'fotos/ara_aljuwayr.jpg', 'comun'],
    ['Abdullah Al-Khaibari', 'Arabia Saudita', '🇸🇦', 'Mediocampista', 'fotos/ara_alkhaibari.jpg', 'rara'],
    ['Abdulelah Al-Amri', 'Arabia Saudita', '🇸🇦', 'Defensor', 'fotos/ara_alobud.jpg', 'rara'],
    ['Marwan Al-Sahafi', 'Arabia Saudita', '🇸🇦', 'Delantero', 'fotos/ara_alsahafi.jpg', 'comun'],
    ['Ahmed Al-Ghamdi', 'Arabia Saudita', '🇸🇦', 'Mediocampista', 'fotos/ara_alsanbi.jpg', 'comun'],
    ['Mohammed Al-Shamat', 'Arabia Saudita', '🇸🇦', 'Defensor', 'fotos/ara_alshamat.jpg', 'comun'],
    ['Saleh Al-Shehri', 'Arabia Saudita', '🇸🇦', 'Delantero', 'fotos/ara_alsheri.jpg', 'epica'],
    ['Hassan Al-Tambakti', 'Arabia Saudita', '🇸🇦', 'Defensor', 'fotos/ara_altambakti.jpg', 'rara'],
    ['Ayman Yahya', 'Arabia Saudita', '🇸🇦', 'Delantero', 'fotos/ara_thikri.jpg', 'comun'],

    // --- REPÚBLICA DEMOCRÁTICA DEL CONGO ---
    ['Cédric Bakambu', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_bakambu.jpg', 'epica'],
    ['Aaron Wan-Bissaka', 'Congo', '🇨🇩', 'Defensor', 'fotos/con_bissaka.jpg', 'epica'],
    ['Brian Cipenga', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_cipenga.jpg', 'comun'], 
    ['Meschack Elia', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_elia.jpg', 'rara'],
    ['Joris Kayembe', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_kayembe.jpg', 'rara'],
    ['Edo Kayembe', 'Congo', '🇨🇩', 'Mediocampista', 'fotos/con_kayembe-.jpg', 'comun'], 
    ['Arthur Masuaku', 'Congo', '🇨🇩', 'Defensor', 'fotos/con_masuaku.jpg', 'rara'],
    ['Fiston Mayele', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_mayele.jpg', 'comun'],
    ['Chancel Mbemba', 'Congo', '🇨🇩', 'Defensor', 'fotos/con_mbemba.jpg', 'legendaria'],
    ['Nathanaël Mbuku', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_mbuku.jpg', 'comun'],
    ['Lionel Mpasi', 'Congo', '🇨🇩', 'Arquero', 'fotos/con_mpasi.jpg', 'comun'],
    ['Ngal\'ayel Mukau', 'Congo', '🇨🇩', 'Mediocampista', 'fotos/con_mukau.jpg', 'comun'],
    ['Charles Pickel', 'Congo', '🇨🇩', 'Mediocampista', 'fotos/con_pickel.jpg', 'comun'],
    ['Axel Tuanzebe', 'Congo', '🇨🇩', 'Defensor', 'fotos/con_tuanzebe.jpg', 'rara'],
    ['Yoane Wissa', 'Congo', '🇨🇩', 'Delantero', 'fotos/con_wissa.jpg', 'epica'],

    // --- EGIPTO ---
    ['Mohamed El-Shenawy', 'Egipto', '🇪🇬', 'Arquero', 'fotos/egi_elshenawy.jpg', 'epica'],
    ['Ahmed Fatouh', 'Egipto', '🇪🇬', 'Defensor', 'fotos/egi_fatouh.jpg', 'rara'],
    ['Mohamed Hany', 'Egipto', '🇪🇬', 'Defensor', 'fotos/egi_handy.jpg', 'rara'], 
    ['Mohanad Lasheen', 'Egipto', '🇪🇬', 'Mediocampista', 'fotos/egi_laheen.jpg', 'comun'], 
    ['Omar Marmoush', 'Egipto', '🇪🇬', 'Delantero', 'fotos/egi_marniysh.jpg', 'epica'],
    ['Ramy Rabia', 'Egipto', '🇪🇬', 'Defensor', 'fotos/egi_rabia.jpg', 'comun'],
    ['Mohamed Salah', 'Egipto', '🇪🇬', 'Delantero', 'fotos/egi_salah.jpg', 'legendaria'],
    ['Ramadan Sobhi', 'Egipto', '🇪🇬', 'Delantero', 'fotos/egi_sobhi.jpg', 'rara'],
    ['Trézéguet', 'Egipto', '🇪🇬', 'Delantero', 'fotos/egi_trezeguet.jpg', 'epica'],

    // --- JORDANIA ---
    ['Abualnadi', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_abualnadi.jpg', 'comun'],
    ['Yazeed Abulaila', 'Jordania', '🇯🇴', 'Arquero', 'fotos/jor_abulaila.jpg', 'rara'],
    ['Ihsan Haddad', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_haddad.jpg', 'rara'],
    ['Mohammad Abu Jamous', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_jamous.jpg', 'comun'],
    ['Mahmoud Al-Mardi', 'Jordania', '🇯🇴', 'Mediocampista', 'fotos/jor_mardi.jpg', 'rara'],
    ['Yazan Al-Naimat', 'Jordania', '🇯🇴', 'Delantero', 'fotos/jor_naimat.jpg', 'rara'],
    ['Obaid', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_obaid.jpg', 'comun'],
    ['Ali Olwan', 'Jordania', '🇯🇴', 'Delantero', 'fotos/jor_olwan.jpg', 'comun'],
    ['Abdallah Rashdan', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_rashdan.jpg', 'comun'],
    ['Noor Al-Rawabdeh', 'Jordania', '🇯🇴', 'Mediocampista', 'fotos/jor_rawabdeh.jpg', 'comun'],
    ['Ibrahim Sadeh', 'Jordania', '🇯🇴', 'Mediocampista', 'fotos/jor_saadeh.jpg', 'comun'], 
    ['Koubaib Al-Sabra', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_sabra.jpg', 'comun'],
    ['Mousa Al-Tamari', 'Jordania', '🇯🇴', 'Delantero', 'fotos/jor_taamari.jpg', 'epica'],
    ['Moouath Taha', 'Jordania', '🇯🇴', 'Defensor', 'fotos/jor_taha.jpg', 'comun'],
    ['Mohammad Abu Zrayq', 'Jordania', '🇯🇴', 'Delantero', 'fotos/jor_zrayq.jpg', 'comun'],

    // --- SUDÁFRICA ---
    ['Oswin Appollis', 'Sudáfrica', '🇿🇦', 'Delantero', 'fotos/sud_appollis.jpg', 'rara'],
    ['Sipho Chaine', 'Sudáfrica', '🇿🇦', 'Arquero', 'fotos/sud_cahine.jpg', 'comun'], 
    ['Samukele Kabini', 'Sudáfrica', '🇿🇦', 'Defensor', 'fotos/sud_kabini.jpg', 'comun'], 
    ['Thalente Mbatha', 'Sudáfrica', '🇿🇦', 'Mediocampista', 'fotos/sud_mbatha.jpg', 'comun'], 
    ['Sipho Mbule', 'Sudáfrica', '🇿🇦', 'Mediocampista', 'fotos/sud_mbule.jpg', 'comun'],
    ['Khuliso Mudau', 'Sudáfrica', '🇿🇦', 'Defensor', 'fotos/sud_mudau.jpg', 'rara'],
    ['Khulumani Ndamane', 'Sudáfrica', '🇿🇦', 'Defensor', 'fotos/sud_ndamane.jpg', 'rara'], 
    ['Siyabonga Ngezana', 'Sudáfrica', '🇿🇦', 'Defensor', 'fotos/sud_negezana.jpg', 'rara'],
    ['Mohau Nkota', 'Sudáfrica', '🇿🇦', 'Defensor', 'fotos/sud_nkota.jpg', 'comun'], 
    ['Iqraam Rayners', 'Sudáfrica', '🇿🇦', 'Delantero', 'fotos/sud_rayners.jpg', 'comun'],
    ['Ronwen Williams', 'Sudáfrica', '🇿🇦', 'Arquero', 'fotos/sud_williams.jpg', 'epica'],

    // --- CABO VERDE ---
    ['Patrick Andrade', 'Cabo Verde', '🇨🇻', 'Mediocampista', 'fotos/ver_andrade.jpg', 'comun'],
    ['Bebé', 'Cabo Verde', '🇨🇻', 'Delantero', 'fotos/ver_bebe.jpg', 'epica'],
    ['Jovane Cabral', 'Cabo Verde', '🇨🇻', 'Delantero', 'fotos/ver_cabral.jpg', 'epica'],
    ['Logan Costa', 'Cabo Verde', '🇨🇻', 'Defensor', 'fotos/ver_costa.jpg', 'rara'],
    ['Diney', 'Cabo Verde', '🇨🇻', 'Defensor', 'fotos/ver_dinev.jpg', 'comun'], 
    ['Deroy Duarte', 'Cabo Verde', '🇨🇻', 'Mediocampista', 'fotos/ver_duarte.jpg', 'rara'],
    ['Dailon Livramento', 'Cabo Verde', '🇨🇻', 'Delantero', 'fotos/ver_livramento.jpg', 'comun'], 
    ['Ryan Mendes', 'Cabo Verde', '🇨🇻', 'Delantero', 'fotos/ver_mendes.jpg', 'legendaria'],
    ['Steven Moreira', 'Cabo Verde', '🇨🇻', 'Defensor', 'fotos/ver_moreira.jpg', 'rara'],
    ['João Paulo', 'Cabo Verde', '🇨🇻', 'Mediocampista', 'fotos/ver_paulo.jpg', 'comun'],
    ['Pico', 'Cabo Verde', '🇨🇻', 'Defensor', 'fotos/ver_pico.jpg', 'rara'],
    ['Jamiro Monteiro', 'Cabo Verde', '🇨🇻', 'Mediocampista', 'fotos/ver_pina.jpg', 'rara'], 
    ['Semedo', 'Cabo Verde', '🇨🇻', 'Mediocampista', 'fotos/ver_semedo.jpg', 'comun'],
    ['Wagner Pina', 'Cabo Verde', '🇨🇻', 'Defensor', 'fotos/ver_semedo-.jpg', 'comun'], 
    ['Vozinha', 'Cabo Verde', '🇨🇻', 'Arquero', 'fotos/ver_vozinha.jpg', 'rara'],

    // --- NUEVA ZELANDA ---
    ['Kosta Barbarouses', 'Nueva Zelanda', '🇳🇿', 'Delantero', 'fotos/zel_barbarouses.jpg', 'rara'], 
    ['Joe Bell', 'Nueva Zelanda', '🇳🇿', 'Mediocampista', 'fotos/zel_bell.jpg', 'rara'], 
    ['Michael Boxall', 'Nueva Zelanda', '🇳🇿', 'Defensor', 'fotos/zel_boxall.jpg', 'comun'], 
    ['Liberato Cacace', 'Nueva Zelanda', '🇳🇿', 'Defensor', 'fotos/zel_cacace.jpg', 'epica'], 
    ['Max Crocombe', 'Nueva Zelanda', '🇳🇿', 'Arquero', 'fotos/zel_crocombe.jpg', 'comun'], 
    ['Matthew Garbett', 'Nueva Zelanda', '🇳🇿', 'Mediocampista', 'fotos/zel_garbett.jpg', 'rara'], 
    ['Callum McCowatt', 'Nueva Zelanda', '🇳🇿', 'Delantero', 'fotos/zel_mccowatt.jpg', 'comun'], 
    ['Alex Paulsen', 'Nueva Zelanda', '🇳🇿', 'Arquero', 'fotos/zel_paulsen.jpg', 'rara'], 
    ['Tim Payne', 'Nueva Zelanda', '🇳🇿', 'Defensor', 'fotos/zel_payne.jpg', 'comun'], 
    ['Marko Stamenic', 'Nueva Zelanda', '🇳🇿', 'Mediocampista', 'fotos/zel_stamenic.jpg', 'epica'], 
    ['Finn Surman', 'Nueva Zelanda', '🇳🇿', 'Defensor', 'fotos/zel_surman.jpg', 'comun'], 
    ['Ryan Thomas', 'Nueva Zelanda', '🇳🇿', 'Mediocampista', 'fotos/zel_thomas.jpg', 'comun'], 
    ['Francis de Vries', 'Nueva Zelanda', '🇳🇿', 'Defensor', 'fotos/zel_vries.jpg', 'comun'], 
    ['Chris Wood', 'Nueva Zelanda', '🇳🇿', 'Delantero', 'fotos/zel_wood.jpg', 'legendaria']
];

module.exports = jugadoresMundial;